version: '3.1'
services:
    app:
        build:
            dockerfile: deploy/local/Dockerfile
            context: ./
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - ./:/app
